// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContextEntry = `-- name: DeleteContextEntry :exec
DELETE FROM context_entries WHERE id = $1
`

func (q *Queries) DeleteContextEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContextEntry, id)
	return err
}

const getContextEntry = `-- name: GetContextEntry :one
SELECT id, category, key, value, is_active, created_at, updated_at FROM context_entries WHERE id = $1
`

func (q *Queries) GetContextEntry(ctx context.Context, id pgtype.UUID) (ContextEntry, error) {
	row := q.db.QueryRow(ctx, getContextEntry, id)
	var i ContextEntry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveContextEntries = `-- name: ListActiveContextEntries :many
SELECT id, category, key, value, is_active, created_at, updated_at FROM context_entries
WHERE is_active = true
ORDER BY category, key
`

func (q *Queries) ListActiveContextEntries(ctx context.Context) ([]ContextEntry, error) {
	rows, err := q.db.Query(ctx, listActiveContextEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextEntry
	for rows.Next() {
		var i ContextEntry
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextEntries = `-- name: ListContextEntries :many
SELECT id, category, key, value, is_active, created_at, updated_at FROM context_entries
WHERE ($1::TEXT IS NULL OR category = $1)
ORDER BY category, key
`

func (q *Queries) ListContextEntries(ctx context.Context, category *string) ([]ContextEntry, error) {
	rows, err := q.db.Query(ctx, listContextEntries, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContextEntry
	for rows.Next() {
		var i ContextEntry
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleContextEntry = `-- name: ToggleContextEntry :one
UPDATE context_entries SET is_active = $2, updated_at = now()
WHERE id = $1
RETURNING id, category, key, value, is_active, created_at, updated_at
`

type ToggleContextEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive *bool       `json:"is_active"`
}

func (q *Queries) ToggleContextEntry(ctx context.Context, arg ToggleContextEntryParams) (ContextEntry, error) {
	row := q.db.QueryRow(ctx, toggleContextEntry, arg.ID, arg.IsActive)
	var i ContextEntry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContextEntry = `-- name: UpsertContextEntry :one
INSERT INTO context_entries (category, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (category, key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = now()
RETURNING id, category, key, value, is_active, created_at, updated_at
`

type UpsertContextEntryParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

func (q *Queries) UpsertContextEntry(ctx context.Context, arg UpsertContextEntryParams) (ContextEntry, error) {
	row := q.db.QueryRow(ctx, upsertContextEntry, arg.Category, arg.Key, arg.Value)
	var i ContextEntry
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
