// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: day_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDayPlan = `-- name: CreateDayPlan :one
INSERT INTO day_plans (plan_date, status, blocks)
VALUES ($1, $2, $3)
RETURNING id, plan_date, status, blocks, created_at, updated_at
`

type CreateDayPlanParams struct {
	PlanDate pgtype.Date `json:"plan_date"`
	Status   string      `json:"status"`
	Blocks   []byte      `json:"blocks"`
}

func (q *Queries) CreateDayPlan(ctx context.Context, arg CreateDayPlanParams) (DayPlan, error) {
	row := q.db.QueryRow(ctx, createDayPlan, arg.PlanDate, arg.Status, arg.Blocks)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.PlanDate,
		&i.Status,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlanMessage = `-- name: CreatePlanMessage :one
INSERT INTO plan_messages (plan_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, plan_id, role, content, created_at
`

type CreatePlanMessageParams struct {
	PlanID  pgtype.UUID `json:"plan_id"`
	Role    string      `json:"role"`
	Content string      `json:"content"`
}

func (q *Queries) CreatePlanMessage(ctx context.Context, arg CreatePlanMessageParams) (PlanMessage, error) {
	row := q.db.QueryRow(ctx, createPlanMessage, arg.PlanID, arg.Role, arg.Content)
	var i PlanMessage
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getDayPlanByDate = `-- name: GetDayPlanByDate :one
SELECT id, plan_date, status, blocks, created_at, updated_at FROM day_plans WHERE plan_date = $1
`

func (q *Queries) GetDayPlanByDate(ctx context.Context, planDate pgtype.Date) (DayPlan, error) {
	row := q.db.QueryRow(ctx, getDayPlanByDate, planDate)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.PlanDate,
		&i.Status,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDayPlanByID = `-- name: GetDayPlanByID :one
SELECT id, plan_date, status, blocks, created_at, updated_at FROM day_plans WHERE id = $1
`

func (q *Queries) GetDayPlanByID(ctx context.Context, id pgtype.UUID) (DayPlan, error) {
	row := q.db.QueryRow(ctx, getDayPlanByID, id)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.PlanDate,
		&i.Status,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanMessages = `-- name: GetPlanMessages :many
SELECT id, plan_id, role, content, created_at FROM plan_messages WHERE plan_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetPlanMessages(ctx context.Context, planID pgtype.UUID) ([]PlanMessage, error) {
	rows, err := q.db.Query(ctx, getPlanMessages, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanMessage
	for rows.Next() {
		var i PlanMessage
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentPlans = `-- name: RecentPlans :many
SELECT id, plan_date, status, blocks, created_at, updated_at FROM day_plans ORDER BY plan_date DESC LIMIT $1
`

func (q *Queries) RecentPlans(ctx context.Context, limit int32) ([]DayPlan, error) {
	rows, err := q.db.Query(ctx, recentPlans, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DayPlan
	for rows.Next() {
		var i DayPlan
		if err := rows.Scan(
			&i.ID,
			&i.PlanDate,
			&i.Status,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDayPlanBlocks = `-- name: UpdateDayPlanBlocks :one
UPDATE day_plans SET blocks = $2, updated_at = now()
WHERE id = $1 RETURNING id, plan_date, status, blocks, created_at, updated_at
`

type UpdateDayPlanBlocksParams struct {
	ID     pgtype.UUID `json:"id"`
	Blocks []byte      `json:"blocks"`
}

func (q *Queries) UpdateDayPlanBlocks(ctx context.Context, arg UpdateDayPlanBlocksParams) (DayPlan, error) {
	row := q.db.QueryRow(ctx, updateDayPlanBlocks, arg.ID, arg.Blocks)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.PlanDate,
		&i.Status,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDayPlanStatus = `-- name: UpdateDayPlanStatus :one
UPDATE day_plans SET status = $2, updated_at = now()
WHERE id = $1 RETURNING id, plan_date, status, blocks, created_at, updated_at
`

type UpdateDayPlanStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDayPlanStatus(ctx context.Context, arg UpdateDayPlanStatusParams) (DayPlan, error) {
	row := q.db.QueryRow(ctx, updateDayPlanStatus, arg.ID, arg.Status)
	var i DayPlan
	err := row.Scan(
		&i.ID,
		&i.PlanDate,
		&i.Status,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
