// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: google_auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGoogleAuth = `-- name: DeleteGoogleAuth :exec
DELETE FROM google_auth WHERE user_id = $1
`

func (q *Queries) DeleteGoogleAuth(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGoogleAuth, userID)
	return err
}

const getGoogleAuth = `-- name: GetGoogleAuth :one
SELECT id, access_token, refresh_token, token_expiry, calendar_id, created_at, updated_at, user_id FROM google_auth WHERE user_id = $1
`

func (q *Queries) GetGoogleAuth(ctx context.Context, userID pgtype.UUID) (GoogleAuth, error) {
	row := q.db.QueryRow(ctx, getGoogleAuth, userID)
	var i GoogleAuth
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CalendarID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertGoogleAuth = `-- name: UpsertGoogleAuth :one
INSERT INTO google_auth (user_id, access_token, refresh_token, token_expiry, calendar_id)
VALUES ($5, $1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  token_expiry = EXCLUDED.token_expiry,
  calendar_id = EXCLUDED.calendar_id,
  updated_at = now()
RETURNING id, access_token, refresh_token, token_expiry, calendar_id, created_at, updated_at, user_id
`

type UpsertGoogleAuthParams struct {
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	CalendarID   string             `json:"calendar_id"`
	UserID       pgtype.UUID        `json:"user_id"`
}

func (q *Queries) UpsertGoogleAuth(ctx context.Context, arg UpsertGoogleAuthParams) (GoogleAuth, error) {
	row := q.db.QueryRow(ctx, upsertGoogleAuth,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.CalendarID,
		arg.UserID,
	)
	var i GoogleAuth
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CalendarID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
