// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContextEntry struct {
	ID        pgtype.UUID        `json:"id"`
	Category  string             `json:"category"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DayPlan struct {
	ID        pgtype.UUID        `json:"id"`
	PlanDate  pgtype.Date        `json:"plan_date"`
	Status    string             `json:"status"`
	Blocks    []byte             `json:"blocks"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlanMessage struct {
	ID        pgtype.UUID        `json:"id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Routine struct {
	ID                   pgtype.UUID        `json:"id"`
	Title                string             `json:"title"`
	Category             string             `json:"category"`
	Frequency            string             `json:"frequency"`
	DaysOfWeek           []int32            `json:"days_of_week"`
	PreferredTimeOfDay   pgtype.Text        `json:"preferred_time_of_day"`
	PreferredDurationMin pgtype.Int4        `json:"preferred_duration_min"`
	Notes                pgtype.Text        `json:"notes"`
	IsActive             pgtype.Bool        `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Category         string             `json:"category"`
	Priority         string             `json:"priority"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	EstimatedMinutes pgtype.Int4        `json:"estimated_minutes"`
	ActualMinutes    pgtype.Int4        `json:"actual_minutes"`
	DeadlineType     pgtype.Text        `json:"deadline_type"`
	DeadlineDate     pgtype.Date        `json:"deadline_date"`
	DeadlineDays     pgtype.Int4        `json:"deadline_days"`
	Notes            pgtype.Text        `json:"notes"`
	IsRoutine        pgtype.Bool        `json:"is_routine"`
	RoutineID        pgtype.UUID        `json:"routine_id"`
	TimesDeferred    pgtype.Int4        `json:"times_deferred"`
	LastDeferredAt   pgtype.Timestamptz `json:"last_deferred_at"`
	IsCompleted      pgtype.Bool        `json:"is_completed"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TaskConversation struct {
	ID           pgtype.UUID        `json:"id"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TaskMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
