// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContextEntry struct {
	ID        pgtype.UUID        `json:"id"`
	Category  string             `json:"category"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	IsActive  *bool              `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type DayPlan struct {
	ID             pgtype.UUID        `json:"id"`
	PlanDate       pgtype.Date        `json:"plan_date"`
	Status         string             `json:"status"`
	Blocks         []byte             `json:"blocks"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	PreviousBlocks []byte             `json:"previous_blocks"`
	PreviousStatus *string            `json:"previous_status"`
}

type GoogleAuth struct {
	ID           pgtype.UUID        `json:"id"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	CalendarID   string             `json:"calendar_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       pgtype.UUID        `json:"user_id"`
}

type PlanMessage struct {
	ID        pgtype.UUID        `json:"id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Routine struct {
	ID                   pgtype.UUID        `json:"id"`
	Title                string             `json:"title"`
	Category             string             `json:"category"`
	Frequency            string             `json:"frequency"`
	DaysOfWeek           []int32            `json:"days_of_week"`
	PreferredTimeOfDay   *string            `json:"preferred_time_of_day"`
	PreferredDurationMin *int32             `json:"preferred_duration_min"`
	Notes                *string            `json:"notes"`
	IsActive             *bool              `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PreferredExactTime   *string            `json:"preferred_exact_time"`
	UserID               pgtype.UUID        `json:"user_id"`
}

type Task struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Category         string             `json:"category"`
	Priority         string             `json:"priority"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	EstimatedMinutes *int32             `json:"estimated_minutes"`
	ActualMinutes    *int32             `json:"actual_minutes"`
	DeadlineType     *string            `json:"deadline_type"`
	DeadlineDate     pgtype.Date        `json:"deadline_date"`
	DeadlineDays     *int32             `json:"deadline_days"`
	Notes            *string            `json:"notes"`
	IsRoutine        *bool              `json:"is_routine"`
	RoutineID        pgtype.UUID        `json:"routine_id"`
	TimesDeferred    *int32             `json:"times_deferred"`
	LastDeferredAt   pgtype.Timestamptz `json:"last_deferred_at"`
	IsCompleted      *bool              `json:"is_completed"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UserID           pgtype.UUID        `json:"user_id"`
}

type TaskConversation struct {
	ID           pgtype.UUID        `json:"id"`
	ParentTaskID pgtype.UUID        `json:"parent_task_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserID       pgtype.UUID        `json:"user_id"`
}

type TaskMessage struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	ClerkID         string             `json:"clerk_id"`
	Email           string             `json:"email"`
	DisplayName     *string            `json:"display_name"`
	AnthropicApiKey *string            `json:"anthropic_api_key"`
	DailyAiCap      int32              `json:"daily_ai_cap"`
	AiCallsToday    int32              `json:"ai_calls_today"`
	AiCallsDate     pgtype.Date        `json:"ai_calls_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
