// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1
`

// Placeholder query file so sqlc has something to process.
// Each context spec will add its own query file.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
