// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines WHERE id = $1
`

func (q *Queries) DeleteRoutine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoutine, id)
	return err
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at FROM routines WHERE id = $1
`

func (q *Queries) GetRoutine(ctx context.Context, id pgtype.UUID) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutine, id)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.PreferredTimeOfDay,
		&i.PreferredDurationMin,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at FROM routines
WHERE ($1::BOOLEAN IS NULL OR $1 = false OR is_active = true)
ORDER BY created_at
`

func (q *Queries) ListRoutines(ctx context.Context, activeOnly *bool) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Frequency,
			&i.DaysOfWeek,
			&i.PreferredTimeOfDay,
			&i.PreferredDurationMin,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesForDay = `-- name: ListRoutinesForDay :many
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at FROM routines
WHERE is_active = true
  AND (
    frequency = 'daily'
    OR (frequency = 'weekdays' AND $1::INT BETWEEN 1 AND 5)
    OR (frequency = 'weekly' AND $1::INT = ANY(days_of_week))
    OR (frequency = 'custom' AND $1::INT = ANY(days_of_week))
  )
ORDER BY preferred_time_of_day, title
`

// Used by planner: active routines that apply to a given day-of-week
func (q *Queries) ListRoutinesForDay(ctx context.Context, dollar_1 int32) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutinesForDay, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Frequency,
			&i.DaysOfWeek,
			&i.PreferredTimeOfDay,
			&i.PreferredDurationMin,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutine = `-- name: UpsertRoutine :one
INSERT INTO routines (id, title, category, frequency, days_of_week,
  preferred_time_of_day, preferred_duration_min, notes, is_active)
VALUES (
  COALESCE($1::UUID, gen_random_uuid()),
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  COALESCE($9::BOOLEAN, true)
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  frequency = EXCLUDED.frequency,
  days_of_week = EXCLUDED.days_of_week,
  preferred_time_of_day = EXCLUDED.preferred_time_of_day,
  preferred_duration_min = EXCLUDED.preferred_duration_min,
  notes = EXCLUDED.notes,
  is_active = EXCLUDED.is_active
RETURNING id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at
`

type UpsertRoutineParams struct {
	ID                   pgtype.UUID `json:"id"`
	Title                string      `json:"title"`
	Category             string      `json:"category"`
	Frequency            string      `json:"frequency"`
	DaysOfWeek           []int32     `json:"days_of_week"`
	PreferredTimeOfDay   *string     `json:"preferred_time_of_day"`
	PreferredDurationMin *int32      `json:"preferred_duration_min"`
	Notes                *string     `json:"notes"`
	IsActive             *bool       `json:"is_active"`
}

func (q *Queries) UpsertRoutine(ctx context.Context, arg UpsertRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, upsertRoutine,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Frequency,
		arg.DaysOfWeek,
		arg.PreferredTimeOfDay,
		arg.PreferredDurationMin,
		arg.Notes,
		arg.IsActive,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.PreferredTimeOfDay,
		&i.PreferredDurationMin,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
