// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRoutine = `-- name: DeleteRoutine :exec
DELETE FROM routines WHERE id = $1 AND user_id = $2
`

type DeleteRoutineParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRoutine(ctx context.Context, arg DeleteRoutineParams) error {
	_, err := q.db.Exec(ctx, deleteRoutine, arg.ID, arg.UserID)
	return err
}

const getRoutine = `-- name: GetRoutine :one
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at, preferred_exact_time, user_id FROM routines WHERE id = $1 AND user_id = $2
`

type GetRoutineParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRoutine(ctx context.Context, arg GetRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, getRoutine, arg.ID, arg.UserID)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.PreferredTimeOfDay,
		&i.PreferredDurationMin,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.PreferredExactTime,
		&i.UserID,
	)
	return i, err
}

const listRoutines = `-- name: ListRoutines :many
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at, preferred_exact_time, user_id FROM routines
WHERE user_id = $1
  AND ($2::BOOLEAN IS NULL OR $2 = false OR is_active = true)
ORDER BY created_at
`

type ListRoutinesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	ActiveOnly *bool       `json:"active_only"`
}

func (q *Queries) ListRoutines(ctx context.Context, arg ListRoutinesParams) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutines, arg.UserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Frequency,
			&i.DaysOfWeek,
			&i.PreferredTimeOfDay,
			&i.PreferredDurationMin,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.PreferredExactTime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutinesForDay = `-- name: ListRoutinesForDay :many
SELECT id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at, preferred_exact_time, user_id FROM routines
WHERE user_id = $1
  AND is_active = true
  AND (
    LOWER(frequency) = 'daily'
    OR (LOWER(frequency) = 'weekdays' AND $2::INT BETWEEN 1 AND 5)
    OR (LOWER(frequency) = 'weekly' AND $2::INT = ANY(days_of_week))
    OR (LOWER(frequency) = 'custom' AND $2::INT = ANY(days_of_week))
  )
ORDER BY preferred_exact_time NULLS LAST, preferred_time_of_day, title
`

type ListRoutinesForDayParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	DayOfWeek int32       `json:"day_of_week"`
}

// Used by planner: active routines that apply to a given day-of-week
func (q *Queries) ListRoutinesForDay(ctx context.Context, arg ListRoutinesForDayParams) ([]Routine, error) {
	rows, err := q.db.Query(ctx, listRoutinesForDay, arg.UserID, arg.DayOfWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routine
	for rows.Next() {
		var i Routine
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Frequency,
			&i.DaysOfWeek,
			&i.PreferredTimeOfDay,
			&i.PreferredDurationMin,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.PreferredExactTime,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoutine = `-- name: UpsertRoutine :one
INSERT INTO routines (id, user_id, title, category, frequency, days_of_week,
  preferred_time_of_day, preferred_duration_min, preferred_exact_time, notes, is_active)
VALUES (
  COALESCE($1::UUID, gen_random_uuid()),
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  COALESCE($11::BOOLEAN, true)
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  frequency = EXCLUDED.frequency,
  days_of_week = EXCLUDED.days_of_week,
  preferred_time_of_day = EXCLUDED.preferred_time_of_day,
  preferred_duration_min = EXCLUDED.preferred_duration_min,
  preferred_exact_time = EXCLUDED.preferred_exact_time,
  notes = EXCLUDED.notes,
  is_active = EXCLUDED.is_active
RETURNING id, title, category, frequency, days_of_week, preferred_time_of_day, preferred_duration_min, notes, is_active, created_at, preferred_exact_time, user_id
`

type UpsertRoutineParams struct {
	ID                   pgtype.UUID `json:"id"`
	UserID               pgtype.UUID `json:"user_id"`
	Title                string      `json:"title"`
	Category             string      `json:"category"`
	Frequency            string      `json:"frequency"`
	DaysOfWeek           []int32     `json:"days_of_week"`
	PreferredTimeOfDay   *string     `json:"preferred_time_of_day"`
	PreferredDurationMin *int32      `json:"preferred_duration_min"`
	PreferredExactTime   *string     `json:"preferred_exact_time"`
	Notes                *string     `json:"notes"`
	IsActive             *bool       `json:"is_active"`
}

func (q *Queries) UpsertRoutine(ctx context.Context, arg UpsertRoutineParams) (Routine, error) {
	row := q.db.QueryRow(ctx, upsertRoutine,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Category,
		arg.Frequency,
		arg.DaysOfWeek,
		arg.PreferredTimeOfDay,
		arg.PreferredDurationMin,
		arg.PreferredExactTime,
		arg.Notes,
		arg.IsActive,
	)
	var i Routine
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.PreferredTimeOfDay,
		&i.PreferredDurationMin,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.PreferredExactTime,
		&i.UserID,
	)
	return i, err
}
