// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks SET is_completed = true, completed_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at
`

func (q *Queries) CompleteTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countIncompleteSubtasks = `-- name: CountIncompleteSubtasks :one
SELECT COUNT(*) FROM tasks WHERE parent_id = $1 AND is_completed = false
`

func (q *Queries) CountIncompleteSubtasks(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIncompleteSubtasks, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, category, priority, parent_id, estimated_minutes,
  deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title            string      `json:"title"`
	Category         string      `json:"category"`
	Priority         string      `json:"priority"`
	ParentID         pgtype.UUID `json:"parent_id"`
	EstimatedMinutes *int32      `json:"estimated_minutes"`
	DeadlineType     *string     `json:"deadline_type"`
	DeadlineDate     pgtype.Date `json:"deadline_date"`
	DeadlineDays     *int32      `json:"deadline_days"`
	Notes            *string     `json:"notes"`
	IsRoutine        *bool       `json:"is_routine"`
	RoutineID        pgtype.UUID `json:"routine_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Category,
		arg.Priority,
		arg.ParentID,
		arg.EstimatedMinutes,
		arg.DeadlineType,
		arg.DeadlineDate,
		arg.DeadlineDays,
		arg.Notes,
		arg.IsRoutine,
		arg.RoutineID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTimesDeferred = `-- name: IncrementTimesDeferred :one
UPDATE tasks SET times_deferred = times_deferred + 1, last_deferred_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at
`

func (q *Queries) IncrementTimesDeferred(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, incrementTimesDeferred, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedulableTasks = `-- name: ListSchedulableTasks :many
SELECT id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at FROM tasks
WHERE is_completed = false
  AND (parent_id IS NOT NULL OR (parent_id IS NULL AND estimated_minutes IS NOT NULL))
ORDER BY
  CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 END,
  deadline_date ASC NULLS LAST,
  times_deferred DESC,
  created_at
`

// Used by planner: subtasks OR standalone tasks, incomplete only
func (q *Queries) ListSchedulableTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSchedulableTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Priority,
			&i.ParentID,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.DeadlineType,
			&i.DeadlineDate,
			&i.DeadlineDays,
			&i.Notes,
			&i.IsRoutine,
			&i.RoutineID,
			&i.TimesDeferred,
			&i.LastDeferredAt,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at FROM tasks WHERE parent_id = $1 ORDER BY created_at
`

func (q *Queries) ListSubtasks(ctx context.Context, parentID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Priority,
			&i.ParentID,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.DeadlineType,
			&i.DeadlineDate,
			&i.DeadlineDays,
			&i.Notes,
			&i.IsRoutine,
			&i.RoutineID,
			&i.TimesDeferred,
			&i.LastDeferredAt,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at FROM tasks
WHERE ($1::TEXT IS NULL OR category = $1)
  AND ($2::BOOLEAN = true OR is_completed = false)
  AND parent_id IS NULL
ORDER BY
  CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 WHEN 'low' THEN 3 END,
  created_at DESC
`

type ListTasksParams struct {
	Category         *string `json:"category"`
	IncludeCompleted *bool   `json:"include_completed"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Category, arg.IncludeCompleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Priority,
			&i.ParentID,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.DeadlineType,
			&i.DeadlineDate,
			&i.DeadlineDays,
			&i.Notes,
			&i.IsRoutine,
			&i.RoutineID,
			&i.TimesDeferred,
			&i.LastDeferredAt,
			&i.IsCompleted,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncompleteTask = `-- name: UncompleteTask :one
UPDATE tasks SET is_completed = false, completed_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at
`

func (q *Queries) UncompleteTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, uncompleteTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActualMinutes = `-- name: UpdateActualMinutes :exec
UPDATE tasks SET actual_minutes = actual_minutes + $2, updated_at = now()
WHERE id = $1
`

type UpdateActualMinutesParams struct {
	ID            pgtype.UUID `json:"id"`
	ActualMinutes *int32      `json:"actual_minutes"`
}

func (q *Queries) UpdateActualMinutes(ctx context.Context, arg UpdateActualMinutesParams) error {
	_, err := q.db.Exec(ctx, updateActualMinutes, arg.ID, arg.ActualMinutes)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
  title = COALESCE($2, title),
  category = COALESCE($3, category),
  priority = COALESCE($4, priority),
  estimated_minutes = COALESCE($5, estimated_minutes),
  deadline_type = COALESCE($6, deadline_type),
  deadline_date = COALESCE($7, deadline_date),
  deadline_days = COALESCE($8, deadline_days),
  notes = COALESCE($9, notes),
  routine_id = COALESCE($10, routine_id),
  updated_at = now()
WHERE id = $1
RETURNING id, title, category, priority, parent_id, estimated_minutes, actual_minutes, deadline_type, deadline_date, deadline_days, notes, is_routine, routine_id, times_deferred, last_deferred_at, is_completed, completed_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID               pgtype.UUID `json:"id"`
	Title            *string     `json:"title"`
	Category         *string     `json:"category"`
	Priority         *string     `json:"priority"`
	EstimatedMinutes *int32      `json:"estimated_minutes"`
	DeadlineType     *string     `json:"deadline_type"`
	DeadlineDate     pgtype.Date `json:"deadline_date"`
	DeadlineDays     *int32      `json:"deadline_days"`
	Notes            *string     `json:"notes"`
	RoutineID        pgtype.UUID `json:"routine_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Priority,
		arg.EstimatedMinutes,
		arg.DeadlineType,
		arg.DeadlineDate,
		arg.DeadlineDays,
		arg.Notes,
		arg.RoutineID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Priority,
		&i.ParentID,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.DeadlineType,
		&i.DeadlineDate,
		&i.DeadlineDays,
		&i.Notes,
		&i.IsRoutine,
		&i.RoutineID,
		&i.TimesDeferred,
		&i.LastDeferredAt,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
