// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskConversation = `-- name: CreateTaskConversation :one
INSERT INTO task_conversations (user_id, status) VALUES ($1, 'active')
RETURNING id, parent_task_id, status, created_at, user_id
`

func (q *Queries) CreateTaskConversation(ctx context.Context, userID pgtype.UUID) (TaskConversation, error) {
	row := q.db.QueryRow(ctx, createTaskConversation, userID)
	var i TaskConversation
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createTaskMessage = `-- name: CreateTaskMessage :one
INSERT INTO task_messages (conversation_id, role, content) VALUES ($1, $2, $3)
RETURNING id, conversation_id, role, content, created_at
`

type CreateTaskMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
}

func (q *Queries) CreateTaskMessage(ctx context.Context, arg CreateTaskMessageParams) (TaskMessage, error) {
	row := q.db.QueryRow(ctx, createTaskMessage, arg.ConversationID, arg.Role, arg.Content)
	var i TaskMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskConversation = `-- name: GetTaskConversation :one
SELECT id, parent_task_id, status, created_at, user_id FROM task_conversations WHERE id = $1 AND user_id = $2
`

type GetTaskConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTaskConversation(ctx context.Context, arg GetTaskConversationParams) (TaskConversation, error) {
	row := q.db.QueryRow(ctx, getTaskConversation, arg.ID, arg.UserID)
	var i TaskConversation
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getTaskMessages = `-- name: GetTaskMessages :many
SELECT id, conversation_id, role, content, created_at FROM task_messages WHERE conversation_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetTaskMessages(ctx context.Context, conversationID pgtype.UUID) ([]TaskMessage, error) {
	rows, err := q.db.Query(ctx, getTaskMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskMessage
	for rows.Next() {
		var i TaskMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTaskConversationParent = `-- name: LinkTaskConversationParent :one
UPDATE task_conversations SET parent_task_id = $2 WHERE id = $1 AND user_id = $3
RETURNING id, parent_task_id, status, created_at, user_id
`

type LinkTaskConversationParentParams struct {
	ID           pgtype.UUID `json:"id"`
	ParentTaskID pgtype.UUID `json:"parent_task_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) LinkTaskConversationParent(ctx context.Context, arg LinkTaskConversationParentParams) (TaskConversation, error) {
	row := q.db.QueryRow(ctx, linkTaskConversationParent, arg.ID, arg.ParentTaskID, arg.UserID)
	var i TaskConversation
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const updateTaskConversationStatus = `-- name: UpdateTaskConversationStatus :one
UPDATE task_conversations SET status = $2 WHERE id = $1 AND user_id = $3
RETURNING id, parent_task_id, status, created_at, user_id
`

type UpdateTaskConversationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTaskConversationStatus(ctx context.Context, arg UpdateTaskConversationStatusParams) (TaskConversation, error) {
	row := q.db.QueryRow(ctx, updateTaskConversationStatus, arg.ID, arg.Status, arg.UserID)
	var i TaskConversation
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
