// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAICallsToday = `-- name: GetAICallsToday :one
SELECT CASE WHEN ai_calls_date = CURRENT_DATE THEN ai_calls_today ELSE 0 END AS calls_today
FROM users WHERE id = $1
`

func (q *Queries) GetAICallsToday(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getAICallsToday, id)
	var calls_today int32
	err := row.Scan(&calls_today)
	return calls_today, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, email, display_name, anthropic_api_key, daily_ai_cap, ai_calls_today, ai_calls_date, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.DisplayName,
		&i.AnthropicApiKey,
		&i.DailyAiCap,
		&i.AiCallsToday,
		&i.AiCallsDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAICallsToday = `-- name: IncrementAICallsToday :one
UPDATE users SET
  ai_calls_today = CASE
    WHEN ai_calls_date = CURRENT_DATE THEN ai_calls_today + 1
    ELSE 1
  END,
  ai_calls_date = CURRENT_DATE,
  updated_at = now()
WHERE id = $1
RETURNING ai_calls_today
`

func (q *Queries) IncrementAICallsToday(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementAICallsToday, id)
	var ai_calls_today int32
	err := row.Scan(&ai_calls_today)
	return ai_calls_today, err
}

const upsertUserByClerkID = `-- name: UpsertUserByClerkID :one
INSERT INTO users (clerk_id, email, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE SET
  email = COALESCE(NULLIF(EXCLUDED.email, ''), users.email),
  display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''), users.display_name),
  updated_at = now()
RETURNING id, clerk_id, email, display_name, anthropic_api_key, daily_ai_cap, ai_calls_today, ai_calls_date, created_at, updated_at
`

type UpsertUserByClerkIDParams struct {
	ClerkID     string  `json:"clerk_id"`
	Email       string  `json:"email"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) UpsertUserByClerkID(ctx context.Context, arg UpsertUserByClerkIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByClerkID, arg.ClerkID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.DisplayName,
		&i.AnthropicApiKey,
		&i.DailyAiCap,
		&i.AiCallsToday,
		&i.AiCallsDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
