// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/google/uuid"
)

type ContextEntry struct {
	ID        uuid.UUID       `json:"id"`
	Category  ContextCategory `json:"category"`
	Key       string          `json:"key"`
	Value     string          `json:"value"`
	IsActive  bool            `json:"isActive"`
	CreatedAt DateTime        `json:"createdAt"`
}

type CreateRoutineInput struct {
	Title                string     `json:"title"`
	Category             Category   `json:"category"`
	Frequency            Frequency  `json:"frequency"`
	DaysOfWeek           []int      `json:"daysOfWeek,omitempty"`
	PreferredTimeOfDay   *TimeOfDay `json:"preferredTimeOfDay,omitempty"`
	PreferredDurationMin *int       `json:"preferredDurationMin,omitempty"`
	Notes                *string    `json:"notes,omitempty"`
}

type CreateTaskInput struct {
	Title            string        `json:"title"`
	Category         Category      `json:"category"`
	Priority         Priority      `json:"priority"`
	ParentID         *uuid.UUID    `json:"parentId,omitempty"`
	EstimatedMinutes *int          `json:"estimatedMinutes,omitempty"`
	DeadlineType     *DeadlineType `json:"deadlineType,omitempty"`
	DeadlineDate     *Date         `json:"deadlineDate,omitempty"`
	DeadlineDays     *int          `json:"deadlineDays,omitempty"`
	Notes            *string       `json:"notes,omitempty"`
	RoutineID        *uuid.UUID    `json:"routineId,omitempty"`
}

type DayPlan struct {
	ID        uuid.UUID      `json:"id"`
	PlanDate  Date           `json:"planDate"`
	Status    PlanStatus     `json:"status"`
	Blocks    []*PlanBlock   `json:"blocks"`
	Messages  []*PlanMessage `json:"messages"`
	CreatedAt DateTime       `json:"createdAt"`
	UpdatedAt DateTime       `json:"updatedAt"`
}

type Mutation struct {
}

type PlanBlock struct {
	ID        string     `json:"id"`
	Time      string     `json:"time"`
	Duration  int        `json:"duration"`
	Title     string     `json:"title"`
	Category  Category   `json:"category"`
	TaskID    *uuid.UUID `json:"taskId,omitempty"`
	RoutineID *uuid.UUID `json:"routineId,omitempty"`
	Notes     *string    `json:"notes,omitempty"`
	Skipped   bool       `json:"skipped"`
}

type PlanMessage struct {
	ID        uuid.UUID `json:"id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt DateTime  `json:"createdAt"`
}

type Query struct {
}

type Routine struct {
	ID                   uuid.UUID  `json:"id"`
	Title                string     `json:"title"`
	Category             Category   `json:"category"`
	Frequency            Frequency  `json:"frequency"`
	DaysOfWeek           []int      `json:"daysOfWeek,omitempty"`
	PreferredTimeOfDay   *TimeOfDay `json:"preferredTimeOfDay,omitempty"`
	PreferredDurationMin *int       `json:"preferredDurationMin,omitempty"`
	Notes                *string    `json:"notes,omitempty"`
	IsActive             bool       `json:"isActive"`
}

type Task struct {
	ID               uuid.UUID     `json:"id"`
	Title            string        `json:"title"`
	Category         Category      `json:"category"`
	Priority         Priority      `json:"priority"`
	ParentID         *uuid.UUID    `json:"parentId,omitempty"`
	Parent           *Task         `json:"parent,omitempty"`
	Subtasks         []*Task       `json:"subtasks"`
	EstimatedMinutes *int          `json:"estimatedMinutes,omitempty"`
	ActualMinutes    int           `json:"actualMinutes"`
	DeadlineType     *DeadlineType `json:"deadlineType,omitempty"`
	DeadlineDate     *Date         `json:"deadlineDate,omitempty"`
	DeadlineDays     *int          `json:"deadlineDays,omitempty"`
	Notes            *string       `json:"notes,omitempty"`
	IsRoutine        bool          `json:"isRoutine"`
	Routine          *Routine      `json:"routine,omitempty"`
	TimesDeferred    int           `json:"timesDeferred"`
	IsCompleted      bool          `json:"isCompleted"`
	CompletedAt      *DateTime     `json:"completedAt,omitempty"`
	CreatedAt        DateTime      `json:"createdAt"`
	UpdatedAt        DateTime      `json:"updatedAt"`
}

type TaskConversation struct {
	ID           uuid.UUID      `json:"id"`
	ParentTaskID *uuid.UUID     `json:"parentTaskId,omitempty"`
	Status       string         `json:"status"`
	Messages     []*TaskMessage `json:"messages"`
	CreatedAt    DateTime       `json:"createdAt"`
}

type TaskMessage struct {
	ID        uuid.UUID `json:"id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	CreatedAt DateTime  `json:"createdAt"`
}

type UpdateBlockInput struct {
	Skipped  *bool   `json:"skipped,omitempty"`
	Time     *string `json:"time,omitempty"`
	Duration *int    `json:"duration,omitempty"`
	Notes    *string `json:"notes,omitempty"`
}

type UpdateRoutineInput struct {
	Title                *string    `json:"title,omitempty"`
	Category             *Category  `json:"category,omitempty"`
	Frequency            *Frequency `json:"frequency,omitempty"`
	DaysOfWeek           []int      `json:"daysOfWeek,omitempty"`
	PreferredTimeOfDay   *TimeOfDay `json:"preferredTimeOfDay,omitempty"`
	PreferredDurationMin *int       `json:"preferredDurationMin,omitempty"`
	Notes                *string    `json:"notes,omitempty"`
	IsActive             *bool      `json:"isActive,omitempty"`
}

type UpdateTaskInput struct {
	Title            *string       `json:"title,omitempty"`
	Category         *Category     `json:"category,omitempty"`
	Priority         *Priority     `json:"priority,omitempty"`
	EstimatedMinutes *int          `json:"estimatedMinutes,omitempty"`
	DeadlineType     *DeadlineType `json:"deadlineType,omitempty"`
	DeadlineDate     *Date         `json:"deadlineDate,omitempty"`
	DeadlineDays     *int          `json:"deadlineDays,omitempty"`
	Notes            *string       `json:"notes,omitempty"`
	RoutineID        *uuid.UUID    `json:"routineId,omitempty"`
	IsCompleted      *bool         `json:"isCompleted,omitempty"`
}

type UpsertContextInput struct {
	Category ContextCategory `json:"category"`
	Key      string          `json:"key"`
	Value    string          `json:"value"`
}

type Category string

const (
	CategoryJob       Category = "JOB"
	CategoryInterview Category = "INTERVIEW"
	CategoryProject   Category = "PROJECT"
	CategoryMeal      Category = "MEAL"
	CategoryBaby      Category = "BABY"
	CategoryExercise  Category = "EXERCISE"
	CategoryAdmin     Category = "ADMIN"
)

var AllCategory = []Category{
	CategoryJob,
	CategoryInterview,
	CategoryProject,
	CategoryMeal,
	CategoryBaby,
	CategoryExercise,
	CategoryAdmin,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryJob, CategoryInterview, CategoryProject, CategoryMeal, CategoryBaby, CategoryExercise, CategoryAdmin:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Category) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Category) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContextCategory string

const (
	ContextCategoryLife        ContextCategory = "LIFE"
	ContextCategoryConstraints ContextCategory = "CONSTRAINTS"
	ContextCategoryEquipment   ContextCategory = "EQUIPMENT"
	ContextCategoryPreferences ContextCategory = "PREFERENCES"
	ContextCategoryCustom      ContextCategory = "CUSTOM"
)

var AllContextCategory = []ContextCategory{
	ContextCategoryLife,
	ContextCategoryConstraints,
	ContextCategoryEquipment,
	ContextCategoryPreferences,
	ContextCategoryCustom,
}

func (e ContextCategory) IsValid() bool {
	switch e {
	case ContextCategoryLife, ContextCategoryConstraints, ContextCategoryEquipment, ContextCategoryPreferences, ContextCategoryCustom:
		return true
	}
	return false
}

func (e ContextCategory) String() string {
	return string(e)
}

func (e *ContextCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContextCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContextCategory", str)
	}
	return nil
}

func (e ContextCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContextCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContextCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeadlineType string

const (
	DeadlineTypeHard    DeadlineType = "HARD"
	DeadlineTypeHorizon DeadlineType = "HORIZON"
)

var AllDeadlineType = []DeadlineType{
	DeadlineTypeHard,
	DeadlineTypeHorizon,
}

func (e DeadlineType) IsValid() bool {
	switch e {
	case DeadlineTypeHard, DeadlineTypeHorizon:
		return true
	}
	return false
}

func (e DeadlineType) String() string {
	return string(e)
}

func (e *DeadlineType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeadlineType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeadlineType", str)
	}
	return nil
}

func (e DeadlineType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeadlineType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeadlineType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Frequency string

const (
	FrequencyDaily    Frequency = "DAILY"
	FrequencyWeekdays Frequency = "WEEKDAYS"
	FrequencyWeekly   Frequency = "WEEKLY"
	FrequencyCustom   Frequency = "CUSTOM"
)

var AllFrequency = []Frequency{
	FrequencyDaily,
	FrequencyWeekdays,
	FrequencyWeekly,
	FrequencyCustom,
}

func (e Frequency) IsValid() bool {
	switch e {
	case FrequencyDaily, FrequencyWeekdays, FrequencyWeekly, FrequencyCustom:
		return true
	}
	return false
}

func (e Frequency) String() string {
	return string(e)
}

func (e *Frequency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Frequency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Frequency", str)
	}
	return nil
}

func (e Frequency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Frequency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Frequency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlanStatus string

const (
	PlanStatusDraft    PlanStatus = "DRAFT"
	PlanStatusAccepted PlanStatus = "ACCEPTED"
)

var AllPlanStatus = []PlanStatus{
	PlanStatusDraft,
	PlanStatusAccepted,
}

func (e PlanStatus) IsValid() bool {
	switch e {
	case PlanStatusDraft, PlanStatusAccepted:
		return true
	}
	return false
}

func (e PlanStatus) String() string {
	return string(e)
}

func (e *PlanStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlanStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlanStatus", str)
	}
	return nil
}

func (e PlanStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlanStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlanStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Priority string

const (
	PriorityHigh   Priority = "HIGH"
	PriorityMedium Priority = "MEDIUM"
	PriorityLow    Priority = "LOW"
)

var AllPriority = []Priority{
	PriorityHigh,
	PriorityMedium,
	PriorityLow,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityHigh, PriorityMedium, PriorityLow:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TimeOfDay string

const (
	TimeOfDayMorning   TimeOfDay = "MORNING"
	TimeOfDayMidday    TimeOfDay = "MIDDAY"
	TimeOfDayAfternoon TimeOfDay = "AFTERNOON"
	TimeOfDayEvening   TimeOfDay = "EVENING"
	TimeOfDayAny       TimeOfDay = "ANY"
)

var AllTimeOfDay = []TimeOfDay{
	TimeOfDayMorning,
	TimeOfDayMidday,
	TimeOfDayAfternoon,
	TimeOfDayEvening,
	TimeOfDayAny,
}

func (e TimeOfDay) IsValid() bool {
	switch e {
	case TimeOfDayMorning, TimeOfDayMidday, TimeOfDayAfternoon, TimeOfDayEvening, TimeOfDayAny:
		return true
	}
	return false
}

func (e TimeOfDay) String() string {
	return string(e)
}

func (e *TimeOfDay) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeOfDay(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeOfDay", str)
	}
	return nil
}

func (e TimeOfDay) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeOfDay) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeOfDay) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
