package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"dayos/db"
	"dayos/graph/model"
	"dayos/identity"
	"dayos/planner"
	"fmt"
	"log"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	if err := validateDeadline(input.DeadlineType, input.DeadlineDate, input.DeadlineDays); err != nil {
		return nil, err
	}

	if input.ParentID != nil {
		parent, err := r.TaskStore.GetTask(ctx, uuidToPgtype(*input.ParentID))
		if err != nil {
			return nil, fmt.Errorf("parent task not found: %w", err)
		}
		if parent.ParentID.Valid {
			return nil, fmt.Errorf("only one level of nesting is allowed")
		}
	}

	row, err := r.TaskStore.CreateTask(ctx, taskConverter.ToCreateParams(input))
	if err != nil {
		return nil, fmt.Errorf("creating task: %w", err)
	}
	return taskConverter.FromDB(row), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id uuid.UUID, input model.UpdateTaskInput) (*model.Task, error) {
	if input.IsCompleted != nil {
		if *input.IsCompleted {
			return r.CompleteTask(ctx, id)
		}
		row, err := r.TaskStore.UncompleteTask(ctx, uuidToPgtype(id))
		if err != nil {
			return nil, fmt.Errorf("uncompleting task: %w", err)
		}
		return taskConverter.FromDB(row), nil
	}

	row, err := r.TaskStore.UpdateTask(ctx, taskConverter.ToUpdateParams(id, input))
	if err != nil {
		return nil, fmt.Errorf("updating task: %w", err)
	}
	return taskConverter.FromDB(row), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id uuid.UUID) (bool, error) {
	// Verify task exists
	if _, err := r.TaskStore.GetTask(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("task not found: %w", err)
	}
	if err := r.TaskStore.DeleteTask(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("deleting task: %w", err)
	}
	return true, nil
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	pgID := uuidToPgtype(id)
	task, err := r.TaskStore.GetTask(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching task: %w", err)
	}

	// Check if this is a parent task (has subtasks)
	subtasks, err := r.TaskStore.ListSubtasks(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("listing subtasks: %w", err)
	}
	if len(subtasks) > 0 {
		return nil, fmt.Errorf("cannot complete parent task directly; complete all subtasks instead")
	}

	row, err := r.TaskStore.CompleteTask(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("completing task: %w", err)
	}

	// If this is a subtask, check if all siblings are now complete
	if task.ParentID.Valid {
		count, err := r.TaskStore.CountIncompleteSubtasks(ctx, task.ParentID)
		if err != nil {
			return nil, fmt.Errorf("counting incomplete subtasks: %w", err)
		}
		if count == 0 {
			if _, err := r.TaskStore.CompleteTask(ctx, task.ParentID); err != nil {
				return nil, fmt.Errorf("auto-completing parent: %w", err)
			}
		}
	}

	return taskConverter.FromDB(row), nil
}

// CreateRoutine is the resolver for the createRoutine field.
func (r *mutationResolver) CreateRoutine(ctx context.Context, input model.CreateRoutineInput) (*model.Routine, error) {
	if input.Frequency == model.FrequencyWeekly || input.Frequency == model.FrequencyCustom {
		if len(input.DaysOfWeek) == 0 {
			return nil, fmt.Errorf("daysOfWeek is required for %s frequency", input.Frequency)
		}
	}

	row, err := r.RoutineStore.UpsertRoutine(ctx, routineConverter.ToDB(input))
	if err != nil {
		return nil, fmt.Errorf("creating routine: %w", err)
	}
	return routineConverter.FromDB(row), nil
}

// UpdateRoutine is the resolver for the updateRoutine field.
func (r *mutationResolver) UpdateRoutine(ctx context.Context, id uuid.UUID, input model.UpdateRoutineInput) (*model.Routine, error) {
	existing, err := r.RoutineStore.GetRoutine(ctx, uuidToPgtype(id))
	if err != nil {
		return nil, fmt.Errorf("fetching routine: %w", err)
	}

	row, err := r.RoutineStore.UpsertRoutine(ctx, routineConverter.MergeParams(existing, input))
	if err != nil {
		return nil, fmt.Errorf("updating routine: %w", err)
	}
	return routineConverter.FromDB(row), nil
}

// DeleteRoutine is the resolver for the deleteRoutine field.
func (r *mutationResolver) DeleteRoutine(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.RoutineStore.DeleteRoutine(ctx, uuidToPgtype(id))
	if err != nil {
		return false, fmt.Errorf("deleting routine: %w", err)
	}
	return true, nil
}

// UpsertContext is the resolver for the upsertContext field.
func (r *mutationResolver) UpsertContext(ctx context.Context, input model.UpsertContextInput) (*model.ContextEntry, error) {
	row, err := r.ContextStore.UpsertContextEntry(ctx, contextConverter.ToDB(input))
	if err != nil {
		return nil, fmt.Errorf("upserting context entry: %w", err)
	}
	return contextConverter.FromDB(row), nil
}

// ToggleContext is the resolver for the toggleContext field.
func (r *mutationResolver) ToggleContext(ctx context.Context, id uuid.UUID, isActive bool) (*model.ContextEntry, error) {
	row, err := r.ContextStore.ToggleContextEntry(ctx, db.ToggleContextEntryParams{
		ID:       uuidToPgtype(id),
		IsActive: &isActive,
	})
	if err != nil {
		return nil, fmt.Errorf("toggling context entry: %w", err)
	}
	return contextConverter.FromDB(row), nil
}

// DeleteContext is the resolver for the deleteContext field.
func (r *mutationResolver) DeleteContext(ctx context.Context, id uuid.UUID) (bool, error) {
	if _, err := r.ContextStore.GetContextEntry(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("context entry not found: %w", err)
	}
	if err := r.ContextStore.DeleteContextEntry(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("deleting context entry: %w", err)
	}
	return true, nil
}

// SendPlanMessage is the resolver for the sendPlanMessage field.
func (r *mutationResolver) SendPlanMessage(ctx context.Context, date model.Date, message string) (*model.DayPlan, error) {
	pgDate := pgtype.Date{Time: date.Time, Valid: true}

	// Check if plan exists
	existingPlan, planErr := r.DayPlanStore.GetDayPlanByDate(ctx, pgDate)
	isNewPlan := planErr != nil
	isReplan := !isNewPlan && existingPlan.Status == "accepted"

	// Create plan if it doesn't exist
	if isNewPlan {
		created, err := r.DayPlanStore.CreateDayPlan(ctx, db.CreateDayPlanParams{
			PlanDate: pgDate,
			Status:   "draft",
			Blocks:   []byte("[]"),
		})
		if err != nil {
			return nil, fmt.Errorf("creating plan: %w", err)
		}
		existingPlan = created
	}

	// Save previous state before replanning so user can revert
	if isReplan {
		if err := r.DayPlanStore.SavePreviousState(ctx, db.SavePreviousStateParams{ID: existingPlan.ID}); err != nil {
			log.Printf("warning: failed to save previous plan state: %v", err)
		}
	}

	// Gather context data for the prompt
	input, err := r.buildPlanChatInput(ctx, existingPlan, message, date.Time, isReplan)
	if err != nil {
		return nil, fmt.Errorf("building plan input: %w", err)
	}

	// Call the planner
	output, err := r.Planner.PlanChat(ctx, input)

	// Store messages regardless of success/failure
	// Insert user message
	_, msgErr := r.DayPlanStore.CreatePlanMessage(ctx, db.CreatePlanMessageParams{
		PlanID:  existingPlan.ID,
		Role:    "user",
		Content: message,
	})
	if msgErr != nil {
		return nil, fmt.Errorf("storing user message: %w", msgErr)
	}

	// Store AI response(s)
	if output != nil {
		for _, raw := range output.RawResponses {
			r.DayPlanStore.CreatePlanMessage(ctx, db.CreatePlanMessageParams{
				PlanID:  existingPlan.ID,
				Role:    "assistant",
				Content: raw,
			})
		}
	}

	if err != nil {
		return nil, err
	}

	// Convert planner blocks to model blocks
	aiBlocks := make([]*model.PlanBlock, len(output.Blocks))
	for i, b := range output.Blocks {
		block := &model.PlanBlock{
			ID:       b.ID,
			Time:     b.Time,
			Duration: b.Duration,
			Title:    b.Title,
			Category: model.Category(strings.ToUpper(b.Category)),
			Notes:    b.Notes,
			Skipped:  b.Skipped,
		}
		if b.TaskID != nil && *b.TaskID != "" && *b.TaskID != "null" {
			if uid, uerr := uuid.Parse(*b.TaskID); uerr == nil {
				block.TaskID = &uid
			}
		}
		if b.RoutineID != nil && *b.RoutineID != "" && *b.RoutineID != "null" {
			if uid, uerr := uuid.Parse(*b.RoutineID); uerr == nil {
				block.RoutineID = &uid
			}
		}
		aiBlocks[i] = block
	}

	// For replanning, merge preserved blocks with AI's new blocks
	var modelBlocks []*model.PlanBlock
	if isReplan {
		existing := parseBlocks(existingPlan.Blocks)

		// Build sets of preserved task/routine IDs to detect duplicates
		preservedTaskIDs := make(map[string]bool)
		preservedRoutineIDs := make(map[string]bool)
		for _, b := range existing {
			if b.Done || b.Skipped {
				modelBlocks = append(modelBlocks, b)
				if b.TaskID != nil {
					preservedTaskIDs[b.TaskID.String()] = true
				}
				if b.RoutineID != nil {
					preservedRoutineIDs[b.RoutineID.String()] = true
				}
			}
		}

		// Also preserve past blocks that are neither done nor skipped (they happened but
		// the user just didn't mark them). This prevents them from being lost during replan.
		if input.CurrentTime != "" {
			for _, b := range existing {
				if !b.Done && !b.Skipped && b.Time < input.CurrentTime {
					modelBlocks = append(modelBlocks, b)
					if b.TaskID != nil {
						preservedTaskIDs[b.TaskID.String()] = true
					}
					if b.RoutineID != nil {
						preservedRoutineIDs[b.RoutineID.String()] = true
					}
				}
			}
		}

		// Filter AI blocks: remove duplicates and past-time blocks
		for _, b := range aiBlocks {
			// Drop blocks scheduled in the past
			if input.CurrentTime != "" && b.Time < input.CurrentTime {
				continue
			}
			// Drop blocks that duplicate a preserved task
			if b.TaskID != nil && preservedTaskIDs[b.TaskID.String()] {
				continue
			}
			// Drop blocks that duplicate a preserved routine
			if b.RoutineID != nil && preservedRoutineIDs[b.RoutineID.String()] {
				continue
			}
			modelBlocks = append(modelBlocks, b)
		}

		sort.Slice(modelBlocks, func(i, j int) bool {
			return modelBlocks[i].Time < modelBlocks[j].Time
		})
	} else {
		// For initial plans of today, filter out past-time blocks
		if input.CurrentTime != "" {
			var filtered []*model.PlanBlock
			for _, b := range aiBlocks {
				if b.Time >= input.CurrentTime {
					filtered = append(filtered, b)
				}
			}
			modelBlocks = filtered
		} else {
			modelBlocks = aiBlocks
		}
	}

	blocksData, err := marshalBlocks(modelBlocks)
	if err != nil {
		return nil, fmt.Errorf("marshaling blocks: %w", err)
	}

	// Update blocks
	updated, err := r.DayPlanStore.UpdateDayPlanBlocks(ctx, db.UpdateDayPlanBlocksParams{
		ID:     existingPlan.ID,
		Blocks: blocksData,
	})
	if err != nil {
		return nil, fmt.Errorf("updating blocks: %w", err)
	}

	// If replanning, set status back to draft
	if isReplan {
		updated, err = r.DayPlanStore.UpdateDayPlanStatus(ctx, db.UpdateDayPlanStatusParams{
			ID:     existingPlan.ID,
			Status: "draft",
		})
		if err != nil {
			return nil, fmt.Errorf("resetting plan status: %w", err)
		}
	}

	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// AcceptPlan is the resolver for the acceptPlan field.
func (r *mutationResolver) AcceptPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	pgDate := pgtype.Date{Time: date.Time, Valid: true}
	plan, err := r.DayPlanStore.GetDayPlanByDate(ctx, pgDate)
	if err != nil {
		return nil, fmt.Errorf("No plan exists for this date")
	}
	if plan.Status == "accepted" {
		messages, err := r.DayPlanStore.GetPlanMessages(ctx, plan.ID)
		if err != nil {
			return nil, fmt.Errorf("fetching plan messages: %w", err)
		}
		return dayPlanConverter.FromDB(plan, messages), nil
	}
	updated, err := r.DayPlanStore.UpdateDayPlanStatus(ctx, db.UpdateDayPlanStatusParams{
		ID:     plan.ID,
		Status: "accepted",
	})
	if err != nil {
		return nil, fmt.Errorf("accepting plan: %w", err)
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// RevertPlan is the resolver for the revertPlan field.
func (r *mutationResolver) RevertPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	pgDate := pgtype.Date{Time: date.Time, Valid: true}
	plan, err := r.DayPlanStore.GetDayPlanByDate(ctx, pgDate)
	if err != nil {
		return nil, fmt.Errorf("No plan exists for this date")
	}
	reverted, err := r.DayPlanStore.RevertPlan(ctx, db.RevertPlanParams{ID: plan.ID})
	if err != nil {
		return nil, fmt.Errorf("No previous plan state to revert to")
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, reverted.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(reverted, messages), nil
}

// SkipBlock is the resolver for the skipBlock field.
func (r *mutationResolver) SkipBlock(ctx context.Context, planID uuid.UUID, blockID string) (*model.DayPlan, error) {
	plan, err := r.DayPlanStore.GetDayPlanByID(ctx, uuidToPgtype(planID))
	if err != nil {
		return nil, fmt.Errorf("plan not found: %w", err)
	}
	if plan.Status != "accepted" {
		return nil, fmt.Errorf("Can only skip blocks on an accepted plan")
	}
	blocks := parseBlocks(plan.Blocks)
	found := false
	for _, b := range blocks {
		if b.ID == blockID {
			b.Skipped = true
			found = true
		}
	}
	if !found {
		return nil, fmt.Errorf("Block not found")
	}
	data, err := marshalBlocks(blocks)
	if err != nil {
		return nil, fmt.Errorf("marshaling blocks: %w", err)
	}
	updated, err := r.DayPlanStore.UpdateDayPlanBlocks(ctx, db.UpdateDayPlanBlocksParams{
		ID:     plan.ID,
		Blocks: data,
	})
	if err != nil {
		return nil, fmt.Errorf("updating blocks: %w", err)
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// UnskipBlock is the resolver for the unskipBlock field.
func (r *mutationResolver) UnskipBlock(ctx context.Context, planID uuid.UUID, blockID string) (*model.DayPlan, error) {
	plan, err := r.DayPlanStore.GetDayPlanByID(ctx, uuidToPgtype(planID))
	if err != nil {
		return nil, fmt.Errorf("plan not found: %w", err)
	}
	if plan.Status != "accepted" {
		return nil, fmt.Errorf("Can only unskip blocks on an accepted plan")
	}
	blocks := parseBlocks(plan.Blocks)
	found := false
	for _, b := range blocks {
		if b.ID == blockID {
			b.Skipped = false
			found = true
		}
	}
	if !found {
		return nil, fmt.Errorf("Block not found")
	}
	data, err := marshalBlocks(blocks)
	if err != nil {
		return nil, fmt.Errorf("marshaling blocks: %w", err)
	}
	updated, err := r.DayPlanStore.UpdateDayPlanBlocks(ctx, db.UpdateDayPlanBlocksParams{
		ID:     plan.ID,
		Blocks: data,
	})
	if err != nil {
		return nil, fmt.Errorf("updating blocks: %w", err)
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// CompleteBlock is the resolver for the completeBlock field.
func (r *mutationResolver) CompleteBlock(ctx context.Context, planID uuid.UUID, blockID string) (*model.DayPlan, error) {
	plan, err := r.DayPlanStore.GetDayPlanByID(ctx, uuidToPgtype(planID))
	if err != nil {
		return nil, fmt.Errorf("plan not found: %w", err)
	}
	if plan.Status != "accepted" {
		return nil, fmt.Errorf("Can only complete blocks on an accepted plan")
	}
	blocks := parseBlocks(plan.Blocks)
	var completed *model.PlanBlock
	for _, b := range blocks {
		if b.ID == blockID {
			b.Done = true
			completed = b
		}
	}
	if completed == nil {
		return nil, fmt.Errorf("Block not found")
	}
	data, err := marshalBlocks(blocks)
	if err != nil {
		return nil, fmt.Errorf("marshaling blocks: %w", err)
	}
	updated, err := r.DayPlanStore.UpdateDayPlanBlocks(ctx, db.UpdateDayPlanBlocksParams{
		ID:     plan.ID,
		Blocks: data,
	})
	if err != nil {
		return nil, fmt.Errorf("updating blocks: %w", err)
	}

	// If the block is linked to a task, complete that task too
	if completed.TaskID != nil {
		if _, err := r.CompleteTask(ctx, *completed.TaskID); err != nil {
			// Log but don't fail — block completion is the primary action
			log.Printf("completing linked task %s: %v", completed.TaskID, err)
		}
	}

	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// UpdateBlock is the resolver for the updateBlock field.
func (r *mutationResolver) UpdateBlock(ctx context.Context, planID uuid.UUID, blockID string, input model.UpdateBlockInput) (*model.DayPlan, error) {
	if input.Duration != nil && *input.Duration <= 0 {
		return nil, fmt.Errorf("Duration must be positive")
	}
	plan, err := r.DayPlanStore.GetDayPlanByID(ctx, uuidToPgtype(planID))
	if err != nil {
		return nil, fmt.Errorf("plan not found: %w", err)
	}
	if plan.Status != "accepted" {
		return nil, fmt.Errorf("Can only update blocks on an accepted plan")
	}
	blocks := parseBlocks(plan.Blocks)
	found := false
	for _, b := range blocks {
		if b.ID == blockID {
			found = true
			if input.Skipped != nil {
				b.Skipped = *input.Skipped
			}
			if input.Done != nil {
				b.Done = *input.Done
			}
			if input.Time != nil {
				b.Time = *input.Time
			}
			if input.Duration != nil {
				b.Duration = *input.Duration
			}
			if input.Notes != nil {
				b.Notes = input.Notes
			}
		}
	}
	if !found {
		return nil, fmt.Errorf("Block not found")
	}
	data, err := marshalBlocks(blocks)
	if err != nil {
		return nil, fmt.Errorf("marshaling blocks: %w", err)
	}
	updated, err := r.DayPlanStore.UpdateDayPlanBlocks(ctx, db.UpdateDayPlanBlocksParams{
		ID:     plan.ID,
		Blocks: data,
	})
	if err != nil {
		return nil, fmt.Errorf("updating blocks: %w", err)
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, updated.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(updated, messages), nil
}

// StartTaskConversation is the resolver for the startTaskConversation field.
func (r *mutationResolver) StartTaskConversation(ctx context.Context, message string) (*model.TaskConversation, error) {
	conv, err := r.TaskConversationStore.CreateTaskConversation(ctx)
	if err != nil {
		return nil, fmt.Errorf("creating conversation: %w", err)
	}

	userName := ""
	if u, ok := identity.FromContext(ctx); ok {
		userName = u.DisplayName
	}
	output, err := r.Planner.TaskChat(ctx, nil, message, userName)
	if err != nil {
		return nil, fmt.Errorf("calling AI: %w", err)
	}

	// Store user message
	r.TaskConversationStore.CreateTaskMessage(ctx, db.CreateTaskMessageParams{
		ConversationID: conv.ID,
		Role:           "user",
		Content:        message,
	})

	// Store assistant response
	r.TaskConversationStore.CreateTaskMessage(ctx, db.CreateTaskMessageParams{
		ConversationID: conv.ID,
		Role:           "assistant",
		Content:        output.RawResponse,
	})

	messages, err := r.TaskConversationStore.GetTaskMessages(ctx, conv.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching messages: %w", err)
	}
	return taskConversationConverter.FromDB(conv, messages), nil
}

// SendTaskMessage is the resolver for the sendTaskMessage field.
func (r *mutationResolver) SendTaskMessage(ctx context.Context, conversationID uuid.UUID, message string) (*model.TaskConversation, error) {
	pgID := uuidToPgtype(conversationID)
	conv, err := r.TaskConversationStore.GetTaskConversation(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("conversation not found: %w", err)
	}

	// Load history
	existingMsgs, err := r.TaskConversationStore.GetTaskMessages(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching messages: %w", err)
	}
	history := make([]planner.Message, len(existingMsgs))
	for i, m := range existingMsgs {
		history[i] = planner.Message{Role: m.Role, Content: m.Content}
	}

	taskUserName := ""
	if u, ok := identity.FromContext(ctx); ok {
		taskUserName = u.DisplayName
	}
	output, err := r.Planner.TaskChat(ctx, history, message, taskUserName)
	if err != nil {
		return nil, fmt.Errorf("calling AI: %w", err)
	}

	// Store messages
	r.TaskConversationStore.CreateTaskMessage(ctx, db.CreateTaskMessageParams{
		ConversationID: pgID,
		Role:           "user",
		Content:        message,
	})
	r.TaskConversationStore.CreateTaskMessage(ctx, db.CreateTaskMessageParams{
		ConversationID: pgID,
		Role:           "assistant",
		Content:        output.RawResponse,
	})

	messages, err := r.TaskConversationStore.GetTaskMessages(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching messages: %w", err)
	}
	return taskConversationConverter.FromDB(conv, messages), nil
}

// ConfirmTaskBreakdown is the resolver for the confirmTaskBreakdown field.
func (r *mutationResolver) ConfirmTaskBreakdown(ctx context.Context, conversationID uuid.UUID) ([]*model.Task, error) {
	pgID := uuidToPgtype(conversationID)

	// Find the last assistant message
	messages, err := r.TaskConversationStore.GetTaskMessages(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching messages: %w", err)
	}

	var lastAssistant string
	for i := len(messages) - 1; i >= 0; i-- {
		if messages[i].Role == "assistant" {
			lastAssistant = messages[i].Content
			break
		}
	}
	if lastAssistant == "" {
		return nil, fmt.Errorf("No valid task proposal found. Continue the conversation first.")
	}

	proposal, err := planner.ParseTaskProposal(lastAssistant)
	if err != nil || proposal == nil {
		return nil, fmt.Errorf("No valid task proposal found. Continue the conversation first.")
	}

	// Create parent task
	parentRow, err := r.TaskStore.CreateTask(ctx, db.CreateTaskParams{
		Title:     proposal.Parent.Title,
		Category:  strings.ToLower(proposal.Parent.Category),
		Priority:  strings.ToLower(proposal.Parent.Priority),
		IsRoutine: boolPtrVal(false),
	})
	if err != nil {
		return nil, fmt.Errorf("creating parent task: %w", err)
	}

	// Set deadline on parent if provided
	if proposal.Parent.DeadlineType != nil && *proposal.Parent.DeadlineType != "null" && *proposal.Parent.DeadlineType != "" {
		updateParams := db.UpdateTaskParams{ID: parentRow.ID}
		dt := strings.ToLower(*proposal.Parent.DeadlineType)
		updateParams.DeadlineType = &dt
		if proposal.Parent.DeadlineDate != nil && *proposal.Parent.DeadlineDate != "null" {
			t, err := time.Parse("2006-01-02", *proposal.Parent.DeadlineDate)
			if err == nil {
				updateParams.DeadlineDate = pgtype.Date{Time: t, Valid: true}
			}
		}
		if proposal.Parent.DeadlineDays != nil {
			v := int32(*proposal.Parent.DeadlineDays)
			updateParams.DeadlineDays = &v
		}
		parentRow, _ = r.TaskStore.UpdateTask(ctx, updateParams)
	}

	result := []*model.Task{taskConverter.FromDB(parentRow)}

	// Create subtasks
	for _, sub := range proposal.Subtasks {
		estMin := int32(sub.EstimatedMinutes)
		subRow, err := r.TaskStore.CreateTask(ctx, db.CreateTaskParams{
			Title:            sub.Title,
			Category:         strings.ToLower(sub.Category),
			Priority:         strings.ToLower(proposal.Parent.Priority),
			ParentID:         parentRow.ID,
			EstimatedMinutes: &estMin,
			Notes:            sub.Notes,
			IsRoutine:        boolPtrVal(false),
		})
		if err != nil {
			return nil, fmt.Errorf("creating subtask: %w", err)
		}
		result = append(result, taskConverter.FromDB(subRow))
	}

	// Link conversation to parent and mark completed
	r.TaskConversationStore.LinkTaskConversationParent(ctx, db.LinkTaskConversationParentParams{
		ID:           pgID,
		ParentTaskID: parentRow.ID,
	})
	r.TaskConversationStore.UpdateTaskConversationStatus(ctx, db.UpdateTaskConversationStatusParams{
		ID:     pgID,
		Status: "completed",
	})

	return result, nil
}

// ResolveSkippedBlock is the resolver for the resolveSkippedBlock field.
func (r *mutationResolver) ResolveSkippedBlock(ctx context.Context, planID uuid.UUID, blockID string, intentional bool) (bool, error) {
	plan, err := r.DayPlanStore.GetDayPlanByID(ctx, uuidToPgtype(planID))
	if err != nil {
		return false, fmt.Errorf("plan not found: %w", err)
	}

	blocks := parseBlocks(plan.Blocks)
	var found *model.PlanBlock
	for _, b := range blocks {
		if b.ID == blockID {
			found = b
			break
		}
	}
	if found == nil {
		return false, fmt.Errorf("Block not found")
	}
	if !found.Skipped {
		return false, fmt.Errorf("Block is not skipped")
	}

	// No task_id means nothing to defer (e.g. routine block)
	if found.TaskID == nil {
		return true, nil
	}

	// Intentional skip — no task modifications
	if intentional {
		return true, nil
	}

	// Unintentional skip — increment times_deferred
	_, err = r.TaskStore.IncrementTimesDeferred(ctx, uuidToPgtype(*found.TaskID))
	if err != nil {
		return false, fmt.Errorf("incrementing times deferred: %w", err)
	}
	return true, nil
}

// ConnectGoogleCalendar is the resolver for the connectGoogleCalendar field.
func (r *mutationResolver) ConnectGoogleCalendar(ctx context.Context, code string) (bool, error) {
	if r.Calendar == nil {
		return false, fmt.Errorf("Google Calendar integration not configured")
	}
	if err := r.Calendar.ExchangeCodeAndStore(ctx, code); err != nil {
		return false, fmt.Errorf("connecting Google Calendar: %w", err)
	}
	return true, nil
}

// DisconnectGoogleCalendar is the resolver for the disconnectGoogleCalendar field.
func (r *mutationResolver) DisconnectGoogleCalendar(ctx context.Context) (bool, error) {
	if r.Calendar == nil {
		return false, fmt.Errorf("Google Calendar integration not configured")
	}
	if err := r.Calendar.Disconnect(ctx); err != nil {
		return false, fmt.Errorf("disconnecting Google Calendar: %w", err)
	}
	return true, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, category *model.Category, includeCompleted *bool) ([]*model.Task, error) {
	var catStr *string
	if category != nil {
		s := strings.ToLower(string(*category))
		catStr = &s
	}
	rows, err := r.TaskStore.ListTasks(ctx, db.ListTasksParams{
		Category:         catStr,
		IncludeCompleted: includeCompleted,
	})
	if err != nil {
		return nil, fmt.Errorf("listing tasks: %w", err)
	}
	// Convert all rows and index by ID
	byID := make(map[uuid.UUID]*model.Task, len(rows))
	result := make([]*model.Task, 0, len(rows))
	for _, row := range rows {
		t := taskConverter.FromDB(row)
		byID[t.ID] = t
		result = append(result, t)
	}
	// Wire up subtasks onto their parents
	for _, t := range result {
		if t.ParentID != nil {
			if parent, ok := byID[*t.ParentID]; ok {
				parent.Subtasks = append(parent.Subtasks, t)
			}
		}
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	row, err := r.TaskStore.GetTask(ctx, uuidToPgtype(id))
	if err != nil {
		return nil, nil
	}
	return taskConverter.FromDB(row), nil
}

// Routines is the resolver for the routines field.
func (r *queryResolver) Routines(ctx context.Context, activeOnly *bool) ([]*model.Routine, error) {
	rows, err := r.RoutineStore.ListRoutines(ctx, activeOnly)
	if err != nil {
		return nil, fmt.Errorf("listing routines: %w", err)
	}
	result := make([]*model.Routine, len(rows))
	for i, row := range rows {
		result[i] = routineConverter.FromDB(row)
	}
	return result, nil
}

// ContextEntries is the resolver for the contextEntries field.
func (r *queryResolver) ContextEntries(ctx context.Context, category *model.ContextCategory) ([]*model.ContextEntry, error) {
	var catStr *string
	if category != nil {
		s := strings.ToLower(string(*category))
		catStr = &s
	}
	rows, err := r.ContextStore.ListContextEntries(ctx, catStr)
	if err != nil {
		return nil, fmt.Errorf("listing context entries: %w", err)
	}
	result := make([]*model.ContextEntry, len(rows))
	for i, row := range rows {
		result[i] = contextConverter.FromDB(row)
	}
	return result, nil
}

// DayPlan is the resolver for the dayPlan field.
func (r *queryResolver) DayPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	pgDate := pgtype.Date{Time: date.Time, Valid: true}
	plan, err := r.DayPlanStore.GetDayPlanByDate(ctx, pgDate)
	if err != nil {
		return nil, nil
	}
	messages, err := r.DayPlanStore.GetPlanMessages(ctx, plan.ID)
	if err != nil {
		return nil, fmt.Errorf("fetching plan messages: %w", err)
	}
	return dayPlanConverter.FromDB(plan, messages), nil
}

// RecentPlans is the resolver for the recentPlans field.
func (r *queryResolver) RecentPlans(ctx context.Context, limit *int) ([]*model.DayPlan, error) {
	l := int32(7)
	if limit != nil {
		l = int32(*limit)
	}
	plans, err := r.DayPlanStore.RecentPlans(ctx, l)
	if err != nil {
		return nil, fmt.Errorf("fetching recent plans: %w", err)
	}
	result := make([]*model.DayPlan, len(plans))
	for i, p := range plans {
		messages, err := r.DayPlanStore.GetPlanMessages(ctx, p.ID)
		if err != nil {
			return nil, fmt.Errorf("fetching plan messages: %w", err)
		}
		result[i] = dayPlanConverter.FromDB(p, messages)
	}
	return result, nil
}

// TaskConversation is the resolver for the taskConversation field.
func (r *queryResolver) TaskConversation(ctx context.Context, id uuid.UUID) (*model.TaskConversation, error) {
	pgID := uuidToPgtype(id)
	conv, err := r.TaskConversationStore.GetTaskConversation(ctx, pgID)
	if err != nil {
		return nil, nil
	}
	messages, err := r.TaskConversationStore.GetTaskMessages(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching messages: %w", err)
	}
	return taskConversationConverter.FromDB(conv, messages), nil
}

// CalendarEvents is the resolver for the calendarEvents field.
func (r *queryResolver) CalendarEvents(ctx context.Context, date model.Date) (*model.CalendarEventsPayload, error) {
	if r.Calendar == nil {
		return &model.CalendarEventsPayload{
			Events:    []*model.CalendarEvent{},
			Version:   "",
			Connected: false,
		}, nil
	}
	result, err := r.Calendar.GetEvents(ctx, date.Time)
	if err != nil {
		return nil, fmt.Errorf("fetching calendar events: %w", err)
	}
	events := make([]*model.CalendarEvent, len(result.Events))
	for i, e := range result.Events {
		events[i] = &model.CalendarEvent{
			Title:     e.Title,
			StartTime: e.StartTime,
			Duration:  e.Duration,
			AllDay:    e.AllDay,
		}
	}
	return &model.CalendarEventsPayload{
		Events:    events,
		Version:   result.Version,
		Connected: result.Connected,
	}, nil
}

// GoogleCalendarStatus is the resolver for the googleCalendarStatus field.
func (r *queryResolver) GoogleCalendarStatus(ctx context.Context) (*model.GoogleCalendarStatus, error) {
	if r.Calendar == nil {
		return &model.GoogleCalendarStatus{Connected: false}, nil
	}
	status, err := r.Calendar.GetStatus(ctx)
	if err != nil {
		return nil, fmt.Errorf("checking calendar status: %w", err)
	}
	return &model.GoogleCalendarStatus{
		Connected:    status.Connected,
		CalendarName: status.CalendarName,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
