package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"dayos/graph/model"
	"fmt"

	"github.com/google/uuid"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CreateTask - createTask"))
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id uuid.UUID, input model.UpdateTaskInput) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTask - deleteTask"))
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: CompleteTask - completeTask"))
}

// CreateRoutine is the resolver for the createRoutine field.
func (r *mutationResolver) CreateRoutine(ctx context.Context, input model.CreateRoutineInput) (*model.Routine, error) {
	panic(fmt.Errorf("not implemented: CreateRoutine - createRoutine"))
}

// UpdateRoutine is the resolver for the updateRoutine field.
func (r *mutationResolver) UpdateRoutine(ctx context.Context, id uuid.UUID, input model.UpdateRoutineInput) (*model.Routine, error) {
	panic(fmt.Errorf("not implemented: UpdateRoutine - updateRoutine"))
}

// DeleteRoutine is the resolver for the deleteRoutine field.
func (r *mutationResolver) DeleteRoutine(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteRoutine - deleteRoutine"))
}

// UpsertContext is the resolver for the upsertContext field.
func (r *mutationResolver) UpsertContext(ctx context.Context, input model.UpsertContextInput) (*model.ContextEntry, error) {
	panic(fmt.Errorf("not implemented: UpsertContext - upsertContext"))
}

// DeleteContext is the resolver for the deleteContext field.
func (r *mutationResolver) DeleteContext(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteContext - deleteContext"))
}

// SendPlanMessage is the resolver for the sendPlanMessage field.
func (r *mutationResolver) SendPlanMessage(ctx context.Context, date model.Date, message string) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: SendPlanMessage - sendPlanMessage"))
}

// AcceptPlan is the resolver for the acceptPlan field.
func (r *mutationResolver) AcceptPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: AcceptPlan - acceptPlan"))
}

// SkipBlock is the resolver for the skipBlock field.
func (r *mutationResolver) SkipBlock(ctx context.Context, planID uuid.UUID, blockID string) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: SkipBlock - skipBlock"))
}

// UpdateBlock is the resolver for the updateBlock field.
func (r *mutationResolver) UpdateBlock(ctx context.Context, planID uuid.UUID, blockID string, input model.UpdateBlockInput) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: UpdateBlock - updateBlock"))
}

// StartTaskConversation is the resolver for the startTaskConversation field.
func (r *mutationResolver) StartTaskConversation(ctx context.Context, message string) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: StartTaskConversation - startTaskConversation"))
}

// SendTaskMessage is the resolver for the sendTaskMessage field.
func (r *mutationResolver) SendTaskMessage(ctx context.Context, conversationID uuid.UUID, message string) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: SendTaskMessage - sendTaskMessage"))
}

// ConfirmTaskBreakdown is the resolver for the confirmTaskBreakdown field.
func (r *mutationResolver) ConfirmTaskBreakdown(ctx context.Context, conversationID uuid.UUID) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: ConfirmTaskBreakdown - confirmTaskBreakdown"))
}

// ResolveSkippedBlock is the resolver for the resolveSkippedBlock field.
func (r *mutationResolver) ResolveSkippedBlock(ctx context.Context, planID uuid.UUID, blockID string, intentional bool) (bool, error) {
	panic(fmt.Errorf("not implemented: ResolveSkippedBlock - resolveSkippedBlock"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, category *model.Category, includeCompleted *bool) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: Tasks - tasks"))
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// Routines is the resolver for the routines field.
func (r *queryResolver) Routines(ctx context.Context, activeOnly *bool) ([]*model.Routine, error) {
	panic(fmt.Errorf("not implemented: Routines - routines"))
}

// ContextEntries is the resolver for the contextEntries field.
func (r *queryResolver) ContextEntries(ctx context.Context, category *model.ContextCategory) ([]*model.ContextEntry, error) {
	panic(fmt.Errorf("not implemented: ContextEntries - contextEntries"))
}

// DayPlan is the resolver for the dayPlan field.
func (r *queryResolver) DayPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: DayPlan - dayPlan"))
}

// RecentPlans is the resolver for the recentPlans field.
func (r *queryResolver) RecentPlans(ctx context.Context, limit *int) ([]*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: RecentPlans - recentPlans"))
}

// TaskConversation is the resolver for the taskConversation field.
func (r *queryResolver) TaskConversation(ctx context.Context, id uuid.UUID) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: TaskConversation - taskConversation"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
