package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"dayos/db"
	"dayos/graph/model"
	"fmt"
	"strings"

	"github.com/google/uuid"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	if err := validateDeadline(input.DeadlineType, input.DeadlineDate, input.DeadlineDays); err != nil {
		return nil, err
	}

	if input.ParentID != nil {
		parent, err := r.TaskStore.GetTask(ctx, uuidToPgtype(*input.ParentID))
		if err != nil {
			return nil, fmt.Errorf("parent task not found: %w", err)
		}
		if parent.ParentID.Valid {
			return nil, fmt.Errorf("only one level of nesting is allowed")
		}
	}

	row, err := r.TaskStore.CreateTask(ctx, taskConverter.ToCreateParams(input))
	if err != nil {
		return nil, fmt.Errorf("creating task: %w", err)
	}
	return taskConverter.FromDB(row), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id uuid.UUID, input model.UpdateTaskInput) (*model.Task, error) {
	if input.IsCompleted != nil {
		if *input.IsCompleted {
			return r.CompleteTask(ctx, id)
		}
		row, err := r.TaskStore.UncompleteTask(ctx, uuidToPgtype(id))
		if err != nil {
			return nil, fmt.Errorf("uncompleting task: %w", err)
		}
		return taskConverter.FromDB(row), nil
	}

	row, err := r.TaskStore.UpdateTask(ctx, taskConverter.ToUpdateParams(id, input))
	if err != nil {
		return nil, fmt.Errorf("updating task: %w", err)
	}
	return taskConverter.FromDB(row), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id uuid.UUID) (bool, error) {
	// Verify task exists
	if _, err := r.TaskStore.GetTask(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("task not found: %w", err)
	}
	if err := r.TaskStore.DeleteTask(ctx, uuidToPgtype(id)); err != nil {
		return false, fmt.Errorf("deleting task: %w", err)
	}
	return true, nil
}

// CompleteTask is the resolver for the completeTask field.
func (r *mutationResolver) CompleteTask(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	pgID := uuidToPgtype(id)
	task, err := r.TaskStore.GetTask(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("fetching task: %w", err)
	}

	// Check if this is a parent task (has subtasks)
	subtasks, err := r.TaskStore.ListSubtasks(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("listing subtasks: %w", err)
	}
	if len(subtasks) > 0 {
		return nil, fmt.Errorf("cannot complete parent task directly; complete all subtasks instead")
	}

	row, err := r.TaskStore.CompleteTask(ctx, pgID)
	if err != nil {
		return nil, fmt.Errorf("completing task: %w", err)
	}

	// If this is a subtask, check if all siblings are now complete
	if task.ParentID.Valid {
		count, err := r.TaskStore.CountIncompleteSubtasks(ctx, task.ParentID)
		if err != nil {
			return nil, fmt.Errorf("counting incomplete subtasks: %w", err)
		}
		if count == 0 {
			if _, err := r.TaskStore.CompleteTask(ctx, task.ParentID); err != nil {
				return nil, fmt.Errorf("auto-completing parent: %w", err)
			}
		}
	}

	return taskConverter.FromDB(row), nil
}

// CreateRoutine is the resolver for the createRoutine field.
func (r *mutationResolver) CreateRoutine(ctx context.Context, input model.CreateRoutineInput) (*model.Routine, error) {
	if input.Frequency == model.FrequencyWeekly || input.Frequency == model.FrequencyCustom {
		if len(input.DaysOfWeek) == 0 {
			return nil, fmt.Errorf("daysOfWeek is required for %s frequency", input.Frequency)
		}
	}

	row, err := r.RoutineStore.UpsertRoutine(ctx, routineConverter.ToDB(input))
	if err != nil {
		return nil, fmt.Errorf("creating routine: %w", err)
	}
	return routineConverter.FromDB(row), nil
}

// UpdateRoutine is the resolver for the updateRoutine field.
func (r *mutationResolver) UpdateRoutine(ctx context.Context, id uuid.UUID, input model.UpdateRoutineInput) (*model.Routine, error) {
	existing, err := r.RoutineStore.GetRoutine(ctx, uuidToPgtype(id))
	if err != nil {
		return nil, fmt.Errorf("fetching routine: %w", err)
	}

	row, err := r.RoutineStore.UpsertRoutine(ctx, routineConverter.MergeParams(existing, input))
	if err != nil {
		return nil, fmt.Errorf("updating routine: %w", err)
	}
	return routineConverter.FromDB(row), nil
}

// DeleteRoutine is the resolver for the deleteRoutine field.
func (r *mutationResolver) DeleteRoutine(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.RoutineStore.DeleteRoutine(ctx, uuidToPgtype(id))
	if err != nil {
		return false, fmt.Errorf("deleting routine: %w", err)
	}
	return true, nil
}

// UpsertContext is the resolver for the upsertContext field.
func (r *mutationResolver) UpsertContext(ctx context.Context, input model.UpsertContextInput) (*model.ContextEntry, error) {
	panic(fmt.Errorf("not implemented: UpsertContext - upsertContext"))
}

// DeleteContext is the resolver for the deleteContext field.
func (r *mutationResolver) DeleteContext(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteContext - deleteContext"))
}

// SendPlanMessage is the resolver for the sendPlanMessage field.
func (r *mutationResolver) SendPlanMessage(ctx context.Context, date model.Date, message string) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: SendPlanMessage - sendPlanMessage"))
}

// AcceptPlan is the resolver for the acceptPlan field.
func (r *mutationResolver) AcceptPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: AcceptPlan - acceptPlan"))
}

// SkipBlock is the resolver for the skipBlock field.
func (r *mutationResolver) SkipBlock(ctx context.Context, planID uuid.UUID, blockID string) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: SkipBlock - skipBlock"))
}

// UpdateBlock is the resolver for the updateBlock field.
func (r *mutationResolver) UpdateBlock(ctx context.Context, planID uuid.UUID, blockID string, input model.UpdateBlockInput) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: UpdateBlock - updateBlock"))
}

// StartTaskConversation is the resolver for the startTaskConversation field.
func (r *mutationResolver) StartTaskConversation(ctx context.Context, message string) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: StartTaskConversation - startTaskConversation"))
}

// SendTaskMessage is the resolver for the sendTaskMessage field.
func (r *mutationResolver) SendTaskMessage(ctx context.Context, conversationID uuid.UUID, message string) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: SendTaskMessage - sendTaskMessage"))
}

// ConfirmTaskBreakdown is the resolver for the confirmTaskBreakdown field.
func (r *mutationResolver) ConfirmTaskBreakdown(ctx context.Context, conversationID uuid.UUID) ([]*model.Task, error) {
	panic(fmt.Errorf("not implemented: ConfirmTaskBreakdown - confirmTaskBreakdown"))
}

// ResolveSkippedBlock is the resolver for the resolveSkippedBlock field.
func (r *mutationResolver) ResolveSkippedBlock(ctx context.Context, planID uuid.UUID, blockID string, intentional bool) (bool, error) {
	panic(fmt.Errorf("not implemented: ResolveSkippedBlock - resolveSkippedBlock"))
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, category *model.Category, includeCompleted *bool) ([]*model.Task, error) {
	var catStr *string
	if category != nil {
		s := strings.ToLower(string(*category))
		catStr = &s
	}
	rows, err := r.TaskStore.ListTasks(ctx, db.ListTasksParams{
		Category:         catStr,
		IncludeCompleted: includeCompleted,
	})
	if err != nil {
		return nil, fmt.Errorf("listing tasks: %w", err)
	}
	result := make([]*model.Task, len(rows))
	for i, row := range rows {
		result[i] = taskConverter.FromDB(row)
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id uuid.UUID) (*model.Task, error) {
	row, err := r.TaskStore.GetTask(ctx, uuidToPgtype(id))
	if err != nil {
		return nil, nil
	}
	return taskConverter.FromDB(row), nil
}

// Routines is the resolver for the routines field.
func (r *queryResolver) Routines(ctx context.Context, activeOnly *bool) ([]*model.Routine, error) {
	rows, err := r.RoutineStore.ListRoutines(ctx, activeOnly)
	if err != nil {
		return nil, fmt.Errorf("listing routines: %w", err)
	}
	result := make([]*model.Routine, len(rows))
	for i, row := range rows {
		result[i] = routineConverter.FromDB(row)
	}
	return result, nil
}

// ContextEntries is the resolver for the contextEntries field.
func (r *queryResolver) ContextEntries(ctx context.Context, category *model.ContextCategory) ([]*model.ContextEntry, error) {
	panic(fmt.Errorf("not implemented: ContextEntries - contextEntries"))
}

// DayPlan is the resolver for the dayPlan field.
func (r *queryResolver) DayPlan(ctx context.Context, date model.Date) (*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: DayPlan - dayPlan"))
}

// RecentPlans is the resolver for the recentPlans field.
func (r *queryResolver) RecentPlans(ctx context.Context, limit *int) ([]*model.DayPlan, error) {
	panic(fmt.Errorf("not implemented: RecentPlans - recentPlans"))
}

// TaskConversation is the resolver for the taskConversation field.
func (r *queryResolver) TaskConversation(ctx context.Context, id uuid.UUID) (*model.TaskConversation, error) {
	panic(fmt.Errorf("not implemented: TaskConversation - taskConversation"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
